FROM public.ecr.aws/lambda/python:3.11

# Lambda working directory
WORKDIR /var/task

# Install PROD-only dependencies
COPY requirements/prod.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app ./app

# Lambda entrypoint (Mangum handler)
CMD ["app.main.handler"]
