FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

# --------------------------------------------------
# Dependencies
# --------------------------------------------------
COPY requirements/ ./requirements/
RUN pip install --no-cache-dir -r requirements/prod.txt

# --------------------------------------------------
# Application code
# --------------------------------------------------
COPY app ./app

# --------------------------------------------------
# DEFAULT handler (API)
# Worker Lambda overrides this in Terraform
# --------------------------------------------------
CMD ["app.main.handler"]
