FROM public.ecr.aws/lambda/python:3.11

# Copy both requirements files
COPY requirements.base.txt requirements.base.txt
COPY requirements.lambda.txt requirements.txt

# Install only Lambda-safe dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app ./app

# Lambda handler
CMD ["app.main.handler"]
