FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

COPY requirements/ ./requirements/
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY app ./app

# 🔥 DLQ replay handler
CMD ["app.workers.dlq_replay_worker.handler"]
