FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

COPY requirements/ ./requirements/
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY app ./app

# Worker Lambda → SQS handler ONLY
CMD ["app.workers.sqs_worker.handler"]
