FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

COPY requirements/ ./requirements/
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY app ./app

# API Lambda → Mangum handler ONLY
CMD ["app.main.handler"]
