FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

# --------------------------------------------------
# Dependencies
# --------------------------------------------------
COPY requirements/ ./requirements/
RUN pip install --no-cache-dir -r requirements/prod.txt

# --------------------------------------------------
# Application code
# --------------------------------------------------
COPY app ./app

# --------------------------------------------------
# 🔥 Outbox Publisher Handler
# --------------------------------------------------
CMD ["app.workers.outbox_publisher.handler"]
